- name: Install some basic utilities required by multiple tools
  homebrew:
    name: 
      - gpg
      - curl
      - rlwrap
      - xclip
      - ripgrep # this should be move to the vim role as that's what is requiring it?
      - fzf
    state: present
