- name: Create .local/bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory    

- name: Install some basic utilties require by multiple tasks
  package:
    name: 
      - gpg
      - curl
      - rlwrap
      - xclip
      - ripgrep # this should be move to the vim role as that's what is requiring it?
      - fzf
      - unzip
    state: present
  become: "{{ ansible_facts.distribution != 'MacOSX' }}"


- name: Install asdf 
  import_role:
    name: asdf
  tags:
    - "asdf"
