- name: Setup Environment
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles_repo_url:  git@github.com:michaeldmoser/dotfiles.git

  roles:
    - name: 1password
      tags: ["1password"]
    - name: cheater-cheater
      tags: ["cheater-cheater", "cht.sh"]
    - name: hammerspoon
      tags: ["hammerspoon"]
    # - tmux

  tasks:
    # - import_tasks: ./tasks/dotfiles.yml

