- name: Setup Environment
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: dotfiles_repo_url
      prompt: "Enter your dotfiles repository URL"
      private: no

  tasks:
    - name: Install Git on macOS
      homebrew:
        name: git
        state: latest
      when: ansible_os_family == "Darwin"

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Chezmoi
      hosts: localhost
      gather_facts: no

      tasks:
        - name: Check if Chezmoi is installed
          command: chezmoi version
          register: chezmoi_version
          ignore_errors: yes
          changed_when: false

        - name: Install Chezmoi
          script: 
            cmd: |
              if [ ! -x "$HOME/.local/bin/chezmoi" ]; then
                sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
              fi
          when: chezmoi_version.rc != 0
    - include: ./tasks/asdf.yml

    - name: Clone and apply dotfiles using Chezmoi
      shell: |
        chezmoi init "{{ dotfiles_repo_url }}"
        chezmoi apply
      args:
        executable: /bin/zsh
