- name: Setup Environment
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles_repo_url:  git@github.com:michaeldmoser/dotfiles.git
    asdf_command: "{{ ansible_env.HOME }}/.asdf/bin/asdf"

  # It seems that OSX instances in AWS dont' have a proper SSL Setup
  # Use this only for testing. 
  # module_defaults:
  #   get_url:
  #     validate_certs: false

  vars_prompt:
    - name: computer_name
      prompt: "What would you like to name this computer?"
      private: false

    - name: computer_use_type
      prompt: "Is this a 'work' or 'personal' computer?"
      private: false


  tasks:
    - name: Set the computer name and metadata
      import_role:
        name: name-computer
      tags: ['name-computer']

    - name: zsh
      import_role:
        name: zsh
      tags: ["zsh", "omz", "oh-my-zsh"]

    - name: 1password
      import_role:
        name: 1password
      tags: ["1password"]
        
    - name: cheater-cheater
      import_role:
        name: cheater-cheater
      tags: ["cheater-cheater", "cht.sh"]

    - name: hammerspoon
      import_role:
        name: hammerspoon
      tags: ["hammerspoon"]

    - name: alacritty
      import_role:
        name: alacritty
      tags: ["alacritty"]

    - name: tmux
      import_role:
        name: tmux
      tags: ["tmux"]

    - name: neovim
      import_role:
        name: neovim
      tags: ["neovim"]

    - name: dotfiles
      import_role:
        name: dotfiles
      tags: ["dotfiles"]

