- name: Setup Environment
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles_repo_url:  git@github.com:michaeldmoser/dotfiles.git

  roles:
    - base
    - name: 1password
      tags: ["1password"]
    # - tmux

  tasks:
    # - import_tasks: ./tasks/cheater-cheater.yml
    # - import_tasks: ./tasks/dotfiles.yml

