- name: Include SSH Key from Vault
  include_vars:
    file: ssh_key.vault

- name: Check if Chezmoi is installed
  command: chezmoi --version
  register: chezmoi_version
  ignore_errors: yes
  changed_when: false

- name: Download Chezmoi installer
  get_url: 
    url: https://get.chezmoi.io 
    dest: /tmp/get_chezmoi.sh
  when: chezmoi_version != ""

- name: Install Chezmoi
  shell: |
    eval $(ssh-agent -s)
    echo "{{ private_ssh_key }}" | ssh-add -
    sh /tmp/get_chezmoi.sh -b $HOME/.local/bin init --apply {{ dotfiles_repo_url }}
  when: chezmoi_version != ""

