---
# tasks file for chezmoi
- name: Add asdf plugin if not already added
  shell: |
    {{ asdf_command }} plugin add chezmoi
  register: asdf

- when: asdf.rc == 0
  block:
    - name: Install lastest version
      shell: |
        {{ asdf_command }} install chezmoi latest

    - name: Set global shim
      shell: |
        {{ asdf_command }} global chezmoi latest

    - name: Create config directory
      file:
        path: "{{ ansible_env.HOME }}/.config/chezmoi"
        state: directory

    - name: Create chezmoi configuration file
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/chezmoi/chezmoi.toml"
        create: yes
        marker: "# {mark} chezmoi ANSIBLE MANAGED BLOCK"
        block: |
          [data]
          computerName = "{{ computer_name }}"
          computerUseType = "{{ computer_use_type }}"

