---
# tasks file for zsh
# Only needed for Debian based systems, OSX comes with ZSH
- when: ansible_os_family == 'Debian'
  block: 
    - name: Install ZSH itself
      apt:
        name: zsh
        state: present
      become: yes
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

- name: Check if Oh My ZSH is already installed
  stat:
    path: ~/.config/oh-my-zsh
  register: ohmyzsh

- name: Install Oh My Zsh 
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: ohmyzsh.stat.isdir is not defined

