---
- name: Setup Environment
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: dotfiles_repo_url
      prompt: "Enter your dotfiles repository URL"
      private: no

  tasks:
    - name: Install Git on macOS
      homebrew:
        name: git
        state: latest
      when: ansible_os_family == "Darwin"

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Chezmoi on macOS
      homebrew:
        name: chezmoi
        state: present
      when: ansible_os_family == "Darwin"

    - name: Install Chezmoi on Ubuntu
      apt:
        name: chezmoi
        state: present
      when: ansible_os_family == "Debian"

    - name: Install ASDF
      shell: |
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
      args:
        executable: /bin/zsh

    - name: Clone and apply dotfiles using Chezmoi
      shell: |
        chezmoi init "{{ dotfiles_repo_url }}"
        chezmoi apply
      args:
        executable: /bin/zsh
