- name: Download 1Password GPG key
  get_url:
    url:  https://downloads.1password.com/linux/keys/1password.asc
    dest: /tmp/1password.asc

- name: Install GPG key for 1password
  shell: |
    cat /tmp/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  become: yes
  register: gpg_key_result
  changed_when: "'BEGIN PGP' in gpg_key_result.stdout"

- name: Add 1Password repository
  blockinfile:
    path: /etc/apt/sources.list.d/1password.list
    create: yes
    block: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
  become: yes

- name: Create debSIG policy directory
  file:
    path: /etc/debsig/policies/AC2D62742012EA22/
    state: directory
  become: yes

- name: Download debSIG policy file
  shell: |
    curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
  register: debsig_policy_result
  changed_when: "'BEGIN POLICY' in debsig_policy_result.stdout"
  become: yes

- name: Create debSIG keyrings directory
  file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory
  become: yes

- name: Download debSIG GPG key
  shell: >
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  register: debsig_key_result
  changed_when: "'BEGIN PGP' in debsig_key_result.stdout"
  become: yes

- name: install 1Password GUI
  apt:
    update_cache: yes
    name: 1password
    state: present
  become: yes

- name: Update APT cache and install 1Password CLI
  apt:
    name: 1password-cli
    state: present
  become: yes

